### PR TITLE
Add documentation on how to keep a forked project synched with its upstream Github project.

### PR DESCRIPTION
**Pull request by michaelaltmann**

### CODE REVIEW

**Comment by fawcett** [comment]
Michael, 

What is in this binary file, and what would the process for viewing it?  I think that the preferred way to provide documentation for this project is through the project wiki pages or potentially some additional doc files written in Markdown format in a doc folder in the project repo.  

If wanted to go with dedicated documenation files in the project repo, we should probably have a group decision on our documentation strategy so we don't have to maintain two sets of docs (files and wiki).

It is great that you are participating in the project.  Your data edits and documentation efforts are definitely appreciated.

**Comment by michaelaltmann** [comment]
My challenge was that I created a word doc with step by step screenshots.
These are a pain to author in wiki, but certainly possible. I think I'd
need to upload each screenshot as a separate image and author the wiki page
with links.

**Comment by geospatialem** [comment]
@michaelaltmann - check out this [GitHub Help page](https://help.github.com/articles/issue-attachments). The page will guide you through adding in images to GitHub. You'll be able to go through the same process shown on the page with on the Wiki. 

Let us know if you have any trouble adding in the documentation notes and screenshots. And as David mentioned, thank you for your involvement!

**Comment by fawcett** [comment]
To me, I think that the easiest work flow from Word to Markdown is to copy and paste the text into at text editor and get rid of all of the funky characters.  Paste the text into the GitHub markdown editor and then use the GUI tools to format the text.  You can drag and drop pictures into the editor.

Let us know if you need a hand.

**Comment by geospatialem** [comment]
Hey @michaelaltmann: I'm going to close this PR, but feel free to add the content to the Wiki site. Let us know if you need any assistance adding in the content at next week's meeting, we are happy to help, if needed!

**Pull request closed without merging**
